language: python
python:
  - "3.2"
  - "3.3"

# command to install dependencies
install: "pip install -r pip_requirements.txt --use-mirrors"

# command to run tests
script: export PYTHONPATH='.' ./run_tests.sh
