language: python
python:
  - "3.3"
  - "3.4"

# command to install dependencies
install: "pip install -r pip_requirements.txt --allow-all-external --allow-insecure guess-language-spirit"

# command to run tests
script: PYTHONPATH='.' ./run_tests.sh
